spring:
  datasource:
    url: jdbc:mysql://localhost:3307/coupon_issue?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: coupon_user
    password: coupon_password

  data:
    redis:
      host: localhost
      port: 6380
